server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  port: 8080

spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: com.akiratoriyama.gokufoodapi.infra.h2.GokuH2SQLDialect
        use_sql_comments: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    database-platform: org.hibernate.dialect.H2Dialect
    schema: classpath:schema.sql
    data: classpath:data.sql
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info